# Hand Written Digits Classification Using CNN

## Problem Statement:

* Classify the digit in the image as one of 10 possibile decimals [0,1,2,3,4,5,6,7,8,9]

### Some of the attributes of the dataset:
1. Image (jpg)

## Solution:

* The problem can be solved using Convolutional Neural Networks where Convolution, ReLU, Max Pooling and Artificial Neural Networks Architecture is used for feature mapping and classification.

##  Notes:

1. CNN's learn features of data, automatically during training process.

2. CNN's reduce dimensionality of data, without losing information.

## Importing libraries

In [16]:
#data handling libraries
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import tensorflow.keras.utils as tku

In [17]:
# tensor handling modules
import tensorflow as tf 
from keras.preprocessing.image import ImageDataGenerator

## Image Data Augmentation

In [18]:
augmentor = ImageDataGenerator(rescale=1./255, shear_range=0.2, zoom_range=0.2, horizontal_flip= True)

## Training Set Preparation

In [19]:
training_set = augmentor.flow_from_directory('MNIST/training_set',
                                target_size=(28,28),
                                batch_size= 32,
                                class_mode= 'categorical'
)

Found 37340 images belonging to 10 classes.


## Test Set Preparation

In [20]:
testing_set = augmentor.flow_from_directory('MNIST/test_set',
                                target_size=(28,28),
                                batch_size= 32,
                                class_mode='categorical'
)

Found 4660 images belonging to 10 classes.


## CNN model Building

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense

In [22]:
cnn = Sequential()

Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB



2022-10-14 00:37:27.852203: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-10-14 00:37:27.853230: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


### Input Layer 

### Convolutional Layers + MaxPooling Layers (2 Dimensional)

In [23]:
cnn.add(Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=[28,28,3]))

### Hidden Layers

In [24]:
cnn.add(MaxPool2D(pool_size=2,strides=2))

In [25]:
cnn.add(Conv2D(filters=32, kernel_size=3, activation='relu',))

In [26]:
cnn.add(MaxPool2D(pool_size=2,strides=2))

In [27]:
cnn.add(Flatten())

### Connectiong to ANN

### Dense Layers with Relu activation Function

In [28]:
cnn.add(Dense(units=64,activation='relu'))

### Output Layer with Softmax Activation Function as data is multi class / categorical

In [29]:
cnn.add(Dense(units=10,activation='softmax'))

In [30]:
cnn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 32)        9248      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 32)         0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 800)               0         
                                                                 
 dense (Dense)               (None, 64)                5

## Compiling Model

In [31]:
cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

## Training Model

In [32]:
cnn.fit(x=training_set,validation_data=testing_set,epochs=20)

Epoch 1/20


2022-10-14 00:37:28.981490: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-10-14 00:37:29.253850: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1166/1167 [============================>.] - ETA: 0s - loss: 0.3731 - accuracy: 0.8805

2022-10-14 00:37:52.503726: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.


1167/1167 [==============================] - 26s 22ms/step - loss: 0.3728 - accuracy: 0.8806 - val_loss: 0.1557 - val_accuracy: 0.9526
Epoch 2/20
1167/1167 [==============================] - 24s 21ms/step - loss: 0.1423 - accuracy: 0.9550 - val_loss: 0.1017 - val_accuracy: 0.9723
Epoch 3/20
1167/1167 [==============================] - 23s 20ms/step - loss: 0.1078 - accuracy: 0.9665 - val_loss: 0.1065 - val_accuracy: 0.9661
Epoch 4/20
1167/1167 [==============================] - 25s 21ms/step - loss: 0.0866 - accuracy: 0.9735 - val_loss: 0.0775 - val_accuracy: 0.9749
Epoch 5/20
1167/1167 [==============================] - 25s 21ms/step - loss: 0.0755 - accuracy: 0.9765 - val_loss: 0.0599 - val_accuracy: 0.9800
Epoch 6/20
1167/1167 [==============================] - 24s 20ms/step - loss: 0.0679 - accuracy: 0.9789 - val_loss: 0.0665 - val_accuracy: 0.9764
Epoch 7/20
1167/1167 [==============================] - 24s 21ms/step - loss: 0.0602 - accuracy: 0.9804 - val_loss: 0.0644 - val_accura

## Predicting

In [33]:
from keras.utils import load_img,img_to_array
test_image = load_img('MNIST/single_prediction/img_1.jpg',target_size=(28,28))


In [34]:
test_image

In [35]:
test_img_array = img_to_array(test_image)

In [36]:
test_img_array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [37]:
test_image = np.expand_dims(test_img_array,axis=0)

In [38]:
test_image

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)

In [41]:
results = cnn.predict((test_image))

1/1 [==============================] - 0s 25ms/step


In [42]:
results

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

## Predicting Test set results

In [44]:
if results[0][0] == 1:
      prediction = 'Zero'
elif results[0][1] == 1:
  prediction = 'One'
elif results[0][2] == 1:
  prediction = 'Two'
elif results[0][3] == 1:
  prediction = 'Three'
elif results[0][4] == 1:
  prediction = 'Four'
elif results[0][5] == 1:
  prediction = 'Five'
elif results[0][6] == 1:
  prediction = 'Six'
elif results[0][7] == 1:
  prediction = 'Seven'
elif results[0][8] == 1:
  prediction = 'Eight'
else:
    prediction = 'Nine'

In [45]:
print(prediction)

Two


## Saving the Trained Model

In [46]:
cnn.save('trained_model/model.h5')